// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DoAnTotNghiep.Models;

public partial class ChiTietDonHang
{
    public int MaChiTiet { get; set; }

    public int? MaDonHang { get; set; }

    public int? MaSanPham { get; set; }

    public int? SoLuong { get; set; }

    public decimal? DonGiaLucMua { get; set; }

    public virtual DonHang MaDonHangNavigation { get; set; }

    public virtual SanPham MaSanPhamNavigation { get; set; }
}