// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DoAnTotNghiep.Models;

public partial class LienHe
{
    public int MaLienHe { get; set; }

    public string HoTen { get; set; }

    public string Email { get; set; }

    public string TinNhan { get; set; }

    public DateTime? NgayGui { get; set; }
}